### ISSUE TITLE
Not working when re signin

### ISSUE THREAD

**Issue by techinpark** [developerfect/github_signin#1]
https://github.com/user-attachments/assets/82be39a4-37ac-4437-b109-d49dbfc8d3f8

Thank you for providing a good library.
It works normally on the initial login, but when I try to log in again after logging out, there's a case where it lands on a new page and there's no response when I press continue. Could you help fix this issue?

**Comment by hoangduchuu** [comment]
@techinpark Not for now,
I'm trying to enable cache https://github.com/developerfect/github_signin/blob/main/lib/src/signin_screen.dart#L89 but can't keep the state for now.

If you need to keep your state, I think you should store the `accessToken` from GitHub to local storage, and then check availability before navigating to GithubSigninScreen,
